### ISSUE TITLE
Set the Scheduler as started for default value after each deployment of the api

### ISSUE THREAD

**Issue by berkingurcan** [MinaFoundation/PGT_LeaderBot#21]
After deployment of the api to server, scheduler stops if it is running naturally. Improve de api code for start scheduling automatically.

**Comment by CristinaEche** [comment]
@berkingurcan 

It seems that the scheduler is not starting. I have 4 days in a row of commits without updates, and I re-run the scheduler again today:

<img width="536" alt="image" src="https://github.com/user-attachments/assets/e7e4ad25-ed94-4c93-ab5f-aab6bf724251">

<img width="536" alt="image" src="https://github.com/user-attachments/assets/ca85a97d-83b3-4ea6-828e-454918bc792b">

**Comment by CristinaEche** [comment]
@berkingurcan 

Scheduler issues are happening on staging, I haven't used production because the results differ from staging.

**Comment by CristinaEche** [comment]
September 30 with scheduler active on staging environment:

1. Command: leaderboard create
2. Result: Same data as September 29th:

<img width="520" alt="image" src="https://github.com/user-attachments/assets/3dc7ec79-9f74-45c0-a63c-c89759040d0a">


<img width="520" alt="image" src="https://github.com/user-attachments/assets/3ae4721c-f7f1-4bbb-ab17-1c6d3e6739ef">

3. command: Run task for users from September 1st to 30th
4. results: data updated
5. command: start the scheduler ( again since it seems to not be running)
6. result: Scheduler already active 
7. Problem: scheduler seems to be active but is not since it is not updating the daily results



<img width="520" alt="image" src="https://github.com/user-attachments/assets/7b81a2cb-6697-4997-a240-eb56653bc476">

link to logd: https://monitoring.minaprotocol.tools/d/dded4590-fe09-43d7-8ba7-aae70cf74028/pod-inspect?orgId=1&var-datasource=PBFA97CFB590B2093&var-cluster=staging&var-namespace=governance&var-resource=deployment&var-pods=leader-bot-mongodb&var-filter=&from=1727639391398&to=1727682591398&viewPanel=22
